using System.Globalization;
using System.IO.Compression;
using System.Text;

using Npgsql;

using NpgsqlTypes;

namespace MartenStudio.SampleDomain.Relational;

/// <summary>
/// The rows of the <c>legacy</c> schema, of <c>legacy.customer_credit</c>'s link to the Marten customers,
/// and of <c>studio_sample.app_settings</c>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Table by table, each only when it is empty.</b> A table that already has rows is somebody's -
/// the previous start's, or a developer's edit - and is left alone. A table that is empty is filled,
/// which is also how <c>legacy.customer_credit</c> comes back after Marten's re-seed truncated
/// <c>mt_doc_customer</c> with <c>CASCADE</c> and took it along. Parents are filled before children,
/// so a foreign key is never checked against a table that has not been written yet.
/// </para>
/// <para>
/// <b>Deterministic.</b> Every value is a function of a row number, generated by Postgres from
/// <c>generate_series</c> where it can be and by the few lines of C# below where it cannot (gzip bytes,
/// the Marten customer ids). Two runs of the demo describe the same data, so a screenshot stays true.
/// </para>
/// </remarks>
internal static class LegacyDemoData
{
    /// <summary>Fills every empty demo table.</summary>
    /// <returns>How many rows were written.</returns>
    internal static async Task<int> SeedAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        CancellationToken cancellationToken)
    {
        int rows = 0;

        rows += await SeedWhenEmptyAsync(connection, transaction, "departments", Departments, cancellationToken).ConfigureAwait(false);
        rows += await SeedWhenEmptyAsync(connection, transaction, "employees", Employees, cancellationToken).ConfigureAwait(false);
        rows += await SeedWhenEmptyAsync(connection, transaction, "product_catalogue", ProductCatalogue, cancellationToken).ConfigureAwait(false);

        int stock = await SeedWhenEmptyAsync(connection, transaction, "warehouses", Warehouses, cancellationToken).ConfigureAwait(false);
        stock += await SeedWhenEmptyAsync(connection, transaction, "stock_levels", StockLevels, cancellationToken).ConfigureAwait(false);
        rows += stock;

        rows += await SeedWhenEmptyAsync(connection, transaction, "purchase_orders", PurchaseOrders, cancellationToken).ConfigureAwait(false);
        rows += await SeedWhenEmptyAsync(connection, transaction, "audit_log", AuditLog, cancellationToken).ConfigureAwait(false);
        rows += await SeedIntegrationMessagesAsync(connection, transaction, cancellationToken).ConfigureAwait(false);
        rows += await SeedWhenEmptyAsync(connection, transaction, "sensor_readings", SensorReadings, cancellationToken).ConfigureAwait(false);

        // The populated materialized view is refreshed when what it reads has changed; the one created
        // WITH NO DATA is never refreshed, because being unpopulated is the whole reason it exists.
        if (stock > 0)
        {
            await ExecuteAsync(connection, transaction, "refresh materialized view legacy.stock_by_region", cancellationToken)
                .ConfigureAwait(false);
        }

        rows += await SeedCustomerCreditAsync(connection, transaction, cancellationToken).ConfigureAwait(false);
        rows += await SeedAppSettingsAsync(connection, transaction, cancellationToken).ConfigureAwait(false);

        return rows;
    }

    private static async Task<int> SeedWhenEmptyAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        string table,
        string sql,
        CancellationToken cancellationToken)
    {
        if (await DemoTable.HasRowsAsync(connection, transaction, RelationalDemoSchema.LegacySchemaName, table, cancellationToken)
                .ConfigureAwait(false))
        {
            return 0;
        }

        return await ExecuteAsync(connection, transaction, sql, cancellationToken).ConfigureAwait(false);
    }

    private static async Task<int> ExecuteAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        string sql,
        CancellationToken cancellationToken)
    {
        await using var command = new NpgsqlCommand(sql, connection, transaction);

        // Postgres's own count of inserted and updated rows; the SELECT setval() calls do not add to it.
        return Math.Max(0, await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false));
    }

    // ---------------------------------------------------------------------------------------------
    // Rows that need C#
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// Twelve messages: JSON payloads, three bodies well over the TOAST threshold, and attachments that
    /// are JSON, gzip, a PNG header, CSV text or nothing - the cases a bytea preview has to tell apart.
    /// </summary>
    private static async Task<int> SeedIntegrationMessagesAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        CancellationToken cancellationToken)
    {
        if (await DemoTable.HasRowsAsync(connection, transaction, RelationalDemoSchema.LegacySchemaName, "integration_messages", cancellationToken)
                .ConfigureAwait(false))
        {
            return 0;
        }

        bool hasSender;
        await using (var probe = new NpgsqlCommand(
            """
            select exists (select 1 from pg_catalog.pg_attribute
                           where attrelid = 'legacy.integration_messages'::regclass
                             and attname = 'sender' and not attisdropped)
            """,
            connection,
            transaction))
        {
            hasSender = await probe.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false) is true;
        }

        string sql = hasSender
            ? """
              insert into legacy.integration_messages
                (message_id, channel, payload, raw_body, attachment, received_at, sent_at_local, sender)
              values (@id, @channel, @payload, @body, @attachment, @received, @sent, @sender)
              """
            : """
              insert into legacy.integration_messages
                (message_id, channel, payload, raw_body, attachment, received_at, sent_at_local)
              values (@id, @channel, @payload, @body, @attachment, @received, @sent)
              """;

        await using var batch = new NpgsqlBatch(connection, transaction);

        DateTime receivedBase = new(2026, 9, 20, 6, 0, 0, DateTimeKind.Utc);

        for (int i = 1; i <= 12; i++)
        {
            string channel = Channels[i % Channels.Length];
            string partner = Partners[i % Partners.Length];
            DateTime received = receivedBase.AddMinutes(i * 97);

            var command = new NpgsqlBatchCommand(sql);

            command.Parameters.Add(new NpgsqlParameter("id", NpgsqlDbType.Uuid)
            {
                Value = new Guid(string.Create(CultureInfo.InvariantCulture, $"6c1e5a70-0d0c-4b1a-9e5f-{i:000000000000}")),
            });
            command.Parameters.Add(new NpgsqlParameter("channel", NpgsqlDbType.Text) { Value = channel });
            command.Parameters.Add(new NpgsqlParameter("payload", NpgsqlDbType.Jsonb) { Value = Payload(i, channel, partner) });
            command.Parameters.Add(new NpgsqlParameter("body", NpgsqlDbType.Text) { Value = (object?) RawBody(i, partner) ?? DBNull.Value });
            command.Parameters.Add(new NpgsqlParameter("attachment", NpgsqlDbType.Bytea) { Value = (object?) Attachment(i, partner) ?? DBNull.Value });
            command.Parameters.Add(new NpgsqlParameter("received", NpgsqlDbType.TimestampTz) { Value = received });

            // timestamp without time zone: the sender's wall clock, three hours ahead of UTC, and never
            // converted - some partners do not send one at all.
            command.Parameters.Add(new NpgsqlParameter("sent", NpgsqlDbType.Timestamp)
            {
                Value = i % 4 == 0
                    ? DBNull.Value
                    : DateTime.SpecifyKind(received.AddHours(3).AddMinutes(-2), DateTimeKind.Unspecified),
            });

            if (hasSender)
            {
                // Mixed case on purpose: it is the column type that makes Orders@ and orders@ one sender.
                command.Parameters.Add(new NpgsqlParameter("sender", NpgsqlDbType.Text)
                {
                    Value = (i % 2 == 0 ? "Orders@" : "orders@") + partner.Split(' ')[0] + ".example",
                });
            }

            batch.BatchCommands.Add(command);
        }

        return await batch.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    private static string Payload(int i, string channel, string partner)
    {
        // Three dollars, so that JSON's own "}}" is content rather than the end of a hole.
        string lines = string.Join(
            ",",
            Enumerable.Range(1, 1 + (i % 4)).Select(n => string.Create(
                CultureInfo.InvariantCulture,
                $$$"""{"line":{{{n}}},"sku":"SKU-{{{(i + n) % 20 + 1:000}}}","quantity":{{{(i * n) % 9 + 1}}}}""")));

        string type = i % 3 == 0 ? "DESADV" : "ORDERS";
        string acknowledged = i % 5 != 0 ? "true" : "false";

        return string.Create(
            CultureInfo.InvariantCulture,
            $$$"""{"type":"{{{type}}}","channel":"{{{channel}}}","partner":"{{{partner}}}","sequence":{{{1000 + i}}},"acknowledged":{{{acknowledged}}},"lines":[{{{lines}}}],"meta":{"retries":{{{i % 3}}},"schema":"v2"}}""");
    }

    /// <summary>
    /// An EDIFACT-shaped body: a few hundred characters for most messages, and 12, 24 and 48 KB for three
    /// of them, so that a cell has to be cut on the server rather than streamed whole.
    /// </summary>
    private static string? RawBody(int i, string partner)
    {
        if (i == 5)
        {
            return null;
        }

        int target = i switch
        {
            3 => 12 * 1024,
            7 => 24 * 1024,
            11 => 48 * 1024,
            _ => 300,
        };

        var body = new StringBuilder();
        body.Append(CultureInfo.InvariantCulture, $"UNB+UNOC:3+{partner.Split(' ')[0].ToUpperInvariant()}:ZZ+ACME:ZZ+260920:0600+{i:00000}'");

        for (int n = 1; body.Length < target; n++)
        {
            body.Append(CultureInfo.InvariantCulture, $"\nLIN+{n}++SKU-{(n * 7 + i) % 20 + 1:000}:SA'QTY+21:{(n * i) % 40 + 1}'PRI+AAA:{4.5m + ((n * 13) % 200 / 4m):0.00}'");
        }

        body.Append(CultureInfo.InvariantCulture, $"\nUNZ+1+{i:00000}'");

        return body.ToString();
    }

    private static byte[]? Attachment(int i, string partner)
    {
        switch (i % 5)
        {
            case 1:
                return Encoding.UTF8.GetBytes(string.Create(
                    CultureInfo.InvariantCulture,
                    $$"""{"ack":"{{i:0000}}","partner":"{{partner}}","status":"accepted"}"""));

            case 2:
                using (var buffer = new MemoryStream())
                {
                    using (var gzip = new GZipStream(buffer, CompressionLevel.SmallestSize, leaveOpen: true))
                    {
                        byte[] text = Encoding.UTF8.GetBytes(string.Concat(Enumerable.Repeat("sku;quantity;warehouse\n", 40)));
                        gzip.Write(text);
                    }

                    return buffer.ToArray();
                }

            case 3:
                // A PNG signature and the start of an IHDR chunk: enough for a sniffer to say "image/png".
                return [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
                    0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x40, 0x08, 0x06, 0x00, 0x00, 0x00, (byte) i];

            case 4:
                return Encoding.UTF8.GetBytes("sku;quantity\nSKU-001;4\nSKU-002;12\nSKU-017;1\n");

            default:
                return null;
        }
    }

    /// <summary>
    /// A credit line for most of the seeded Marten customers - not all, so that "referenced by nothing"
    /// is a state the demo has too. Only customers that exist in <c>mt_doc_customer</c> get one.
    /// </summary>
    private static async Task<int> SeedCustomerCreditAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        CancellationToken cancellationToken)
    {
        if (!await DemoTable.ExistsAsync(connection, transaction, RelationalDemoSchema.MartenDocumentSchemaName, "mt_doc_customer", cancellationToken)
                .ConfigureAwait(false)
            || await DemoTable.HasRowsAsync(connection, transaction, RelationalDemoSchema.LegacySchemaName, RelationalDemoSchema.CustomerCreditTable, cancellationToken)
                .ConfigureAwait(false))
        {
            return 0;
        }

        List<Guid> ids = [];
        List<decimal> limits = [];
        List<string> currencies = [];
        List<string> bands = [];
        List<DateTime> reviewed = [];

        for (int i = 1; i <= SampleDataSeeder.CustomerCount; i++)
        {
            if (i % 4 == 0)
            {
                continue;
            }

            ids.Add(SampleDataSeeder.CustomerId(i));
            limits.Add(1_000m * (2 + (i * 7 % 23)));
            currencies.Add(i % 6 == 0 ? "SEK" : "EUR");
            bands.Add(RiskBands[i % RiskBands.Length]);
            reviewed.Add(new DateTime(2026, 4, 1, 9, 0, 0, DateTimeKind.Utc).AddDays(i * 5));
        }

        await using var command = new NpgsqlCommand(
            """
            insert into legacy.customer_credit (customer_id, credit_limit, currency, risk_band, reviewed_at)
            select x.id, x.credit_limit, x.currency, x.risk_band, x.reviewed_at
            from unnest(@ids, @limits, @currencies, @bands, @reviewed)
                   as x(id, credit_limit, currency, risk_band, reviewed_at)
            where exists (select 1 from studio_sample.mt_doc_customer c where c.id = x.id)
            """,
            connection,
            transaction);

        command.Parameters.Add(new NpgsqlParameter("ids", NpgsqlDbType.Array | NpgsqlDbType.Uuid) { Value = ids.ToArray() });
        command.Parameters.Add(new NpgsqlParameter("limits", NpgsqlDbType.Array | NpgsqlDbType.Numeric) { Value = limits.ToArray() });
        command.Parameters.Add(new NpgsqlParameter("currencies", NpgsqlDbType.Array | NpgsqlDbType.Text) { Value = currencies.ToArray() });
        command.Parameters.Add(new NpgsqlParameter("bands", NpgsqlDbType.Array | NpgsqlDbType.Text) { Value = bands.ToArray() });
        command.Parameters.Add(new NpgsqlParameter("reviewed", NpgsqlDbType.Array | NpgsqlDbType.TimestampTz) { Value = reviewed.ToArray() });

        return await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    private static async Task<int> SeedAppSettingsAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        CancellationToken cancellationToken)
    {
        if (!await DemoTable.ExistsAsync(connection, transaction, RelationalDemoSchema.MartenDocumentSchemaName, RelationalDemoSchema.AppSettingsTable, cancellationToken)
                .ConfigureAwait(false)
            || await DemoTable.HasRowsAsync(connection, transaction, RelationalDemoSchema.MartenDocumentSchemaName, RelationalDemoSchema.AppSettingsTable, cancellationToken)
                .ConfigureAwait(false))
        {
            return 0;
        }

        return await ExecuteAsync(connection, transaction, AppSettings, cancellationToken).ConfigureAwait(false);
    }

    private static readonly string[] Channels = ["edi", "webhook", "sftp", "email"];

    private static readonly string[] Partners =
        ["Nordic Packaging Oy", "Baltic Logistics AS", "Svea Tools AB", "Hanse Industrie GmbH", "Pohjolan Kone Oy"];

    private static readonly string[] RiskBands = ["A", "A", "B", "B", "C"];

    // ---------------------------------------------------------------------------------------------
    // Rows Postgres generates
    // ---------------------------------------------------------------------------------------------

    private const string Departments =
        """
        insert into legacy.departments (department_code, name, cost_centre) values
          ('EXE', 'Executive', 'CC-100'),
          ('FIN', 'Finance', 'CC-200'),
          ('OPS', 'Operations', 'CC-300'),
          ('WHS', 'Warehousing', 'CC-310'),
          ('SAL', 'Sales', 'CC-400'),
          ('ITS', 'IT Services', 'CC-500'),
          ('PPL', 'People', 'CC-600')
        """;

    /// <summary>
    /// Forty people: a managing director, six department heads reporting to them, and thirty-three staff
    /// reporting to their head - the self-referencing key three levels deep. Two have left.
    /// </summary>
    private const string Employees =
        """
        insert into legacy.employees
          (employee_id, department_code, manager_id, first_name, last_name, email, hired_on, terminated_on, updated_at)
        select g,
               p.department_code,
               p.manager_id,
               p.first_name,
               p.last_name,
               pg_catalog.translate(pg_catalog.lower(p.first_name || '.' || p.last_name), 'äöå', 'aoa') || '@acme.example',
               date '2012-03-01' + (g * 97) % 4800,
               case when g in (13, 29) then date '2025-11-30' end,
               timestamptz '2026-01-15 09:00:00+00' + g * interval '1 hour'
        from pg_catalog.generate_series(1, 40) as g
        cross join lateral (
          select case when g = 1 then 'EXE'
                      when g <= 7 then (array['FIN', 'OPS', 'WHS', 'SAL', 'ITS', 'PPL'])[g - 1]
                      else (array['FIN', 'OPS', 'WHS', 'SAL', 'ITS', 'PPL'])[1 + (g - 8) % 6] end as department_code,
                 case when g = 1 then null
                      when g <= 7 then 1
                      else 2 + (g - 8) % 6 end as manager_id,
                 (array['Aino', 'Eero', 'Helmi', 'Ilmari', 'Kaisa', 'Lauri', 'Mikko', 'Noora', 'Olli', 'Pia',
                        'Riikka', 'Sami', 'Tuula', 'Ville', 'Anna', 'Jussi', 'Elina', 'Matti', 'Sanna', 'Timo'])[1 + (g * 7) % 20] as first_name,
                 (array['Virtanen', 'Korhonen', 'Mäkinen', 'Nieminen', 'Mäkelä', 'Hämäläinen', 'Laine', 'Heikkinen',
                        'Koskinen', 'Järvinen', 'Lehtonen', 'Lehtinen', 'Saarinen', 'Salminen', 'Heinonen', 'Niemi',
                        'Heikkilä', 'Kinnunen', 'Salonen', 'Turunen', 'Salo', 'Laitinen', 'Tuominen', 'Rantanen',
                        'Karjalainen'])[1 + (g * 11) % 25] as last_name
        ) as p;

        select pg_catalog.setval(pg_catalog.pg_get_serial_sequence('legacy.employees', 'employee_id'),
                                 (select max(employee_id) from legacy.employees));
        """;

    /// <summary>Twenty products across the forty columns, with the gaps a real import has.</summary>
    private const string ProductCatalogue =
        """
        insert into legacy.product_catalogue
          (sku, name, description, category, subcategory, brand, supplier_code, ean, upc, colour,
           size_label, material, weight_g, length_mm, width_mm, height_mm, unit_price, cost_price, currency, vat_rate,
           stock_qty, reorder_level, lead_time_days, discontinued, launched_on, country_of_origin, hs_code, warranty_months, min_order_qty, pack_size,
           shelf_life_days, hazardous, fragile, image_url, notes, created_by, created_at, modified_by, modified_at, import_batch)
        select s.sku,
               i.item || case when g > 10 then ' XL' else '' end,
               'Imported from the 2019 catalogue spreadsheet: ' || pg_catalog.lower(i.item) || '.',
               i.category,
               i.subcategory,
               (array['Nordic Pack', 'Svea', 'Hanse', 'Pohjola'])[1 + g % 4],
               pg_catalog.format('SUP-%s', 100 + g % 7),
               (6400000000000 + g * 1237)::text,
               case when g % 3 = 0 then null else (400000000000 + g * 911)::text end,
               case when g % 2 = 0 then null else (array['black', 'orange', 'grey', 'yellow'])[1 + g % 4] end,

               (array['S', 'M', 'L', 'XL', null])[1 + g % 5],
               (array['steel', 'polypropylene', 'nitrile', 'aluminium', 'cardboard'])[1 + g % 5],
               120 + g * 37,
               100 + g * 11,
               60 + g * 7,
               20 + g * 3,
               round(4.90 + g * 3.15, 2),
               round(2.10 + g * 1.85, 2),
               'EUR',
               25.50,

               (g * 173) % 900,
               50 + (g % 4) * 25,
               7 + g % 21,
               g in (7, 14),
               date '2019-04-01' + g * 45,
               (array['FI', 'SE', 'DE', 'CN', 'PL'])[1 + g % 5],
               pg_catalog.format('%s.%s', 3900 + g % 30, 10 + g % 80),
               case when g % 4 = 0 then null else 12 * (1 + g % 3) end,
               1 + g % 10,
               case when g % 2 = 0 then 12 else 1 end,

               case when i.category = 'consumables' then 730 end,
               g in (3, 17),
               g % 5 = 2,
               'https://cdn.acme.example/catalogue/' || pg_catalog.lower(s.sku) || '.jpg',
               case when g % 6 = 0 then 'Check the pack size against the supplier sheet.' end,
               'import-bot',
               timestamptz '2019-04-01 03:00:00+00' + g * interval '1 minute',
               case when g % 3 = 0 then 'aino.virtanen' end,
               case when g % 3 = 0 then timestamptz '2025-02-10 12:00:00+00' + g * interval '1 day' end,
               'IMP-2019-04'
        from pg_catalog.generate_series(1, 20) as g
        cross join lateral (select pg_catalog.format('SKU-%s', pg_catalog.lpad(g::text, 3, '0')) as sku) as s
        cross join lateral (
          select (array['Pallet wrap', 'Cable ties', 'Box cutter', 'Safety gloves', 'Label printer',
                        'Barcode scanner', 'Tape gun', 'Shelf bin', 'Hand truck', 'Step ladder'])[1 + (g - 1) % 10] as item,
                 (array['consumables', 'consumables', 'tools', 'safety', 'hardware',
                        'hardware', 'tools', 'storage', 'handling', 'handling'])[1 + (g - 1) % 10] as category,
                 (array['wrapping', 'fastening', 'cutting', 'gloves', 'printing',
                        'scanning', 'taping', 'bins', 'trolleys', 'ladders'])[1 + (g - 1) % 10] as subcategory
        ) as i
        """;

    /// <summary>Five warehouses; Hamburg has no address yet (a NULL composite) and no stock.</summary>
    private const string Warehouses =
        """
        insert into legacy.warehouses (region_code, warehouse_no, name, address, opened_on) values
          ('FI', 1, 'Helsinki central', row('Satamakatu 1', 'Helsinki', '00160', 'FI')::legacy.postal_address, date '2009-05-04'),
          ('FI', 2, 'Tampere', row('Hatanpään valtatie 30', 'Tampere', '33100', 'FI')::legacy.postal_address, date '2014-09-01'),
          ('SE', 1, 'Stockholm', row('Frihamnsgatan 20', 'Stockholm', '115 56', 'SE')::legacy.postal_address, date '2017-02-13'),
          ('EE', 1, 'Tallinn', row('Peterburi tee 46', 'Tallinn', '11415', 'EE')::legacy.postal_address, date '2019-06-03'),
          ('DE', 1, 'Hamburg', null, date '2026-10-01')
        """;

    /// <summary>The first twelve products in every warehouse that is open.</summary>
    private const string StockLevels =
        """
        insert into legacy.stock_levels (region_code, warehouse_no, sku, quantity, counted_at)
        select w.region_code,
               w.warehouse_no,
               p.sku,
               (w.warehouse_no * 37 + pg_catalog.ascii(w.region_code) * 11 + p.n * 53) % 400,
               timestamptz '2026-09-01 06:00:00+00' + p.n * interval '7 minutes'
        from legacy.warehouses w
        cross join (
          select c.sku, (row_number() over (order by c.sku))::int as n
          from legacy.product_catalogue c
          order by c.sku
          limit 12
        ) as p
        where w.region_code <> 'DE'
        """;

    /// <summary>
    /// Thirty orders, one to four lines each, and their totals. Explicit ids, then the identity's
    /// sequence moved past them, so a later insert without an id still works.
    /// </summary>
    private const string PurchaseOrders =
        """
        insert into legacy.purchase_orders (order_id, reference, supplier_name, status, requested_by, ordered_on, total, updated_at)
        select g,
               pg_catalog.format('PO-2026-%s', pg_catalog.lpad(g::text, 4, '0')),
               (array['Nordic Packaging Oy', 'Baltic Logistics AS', 'Svea Tools AB', 'Hanse Industrie GmbH', 'Pohjolan Kone Oy'])[1 + g % 5],
               (pg_catalog.enum_range(null::legacy.order_status))[1 + g % 5],
               case when g % 9 = 0 then null else 8 + (g * 5) % 33 end,
               date '2026-01-05' + g * 7,
               0,
               timestamptz '2026-01-05 10:00:00+00' + g * interval '7 days'
        from pg_catalog.generate_series(1, 30) as g;

        select pg_catalog.setval(pg_catalog.pg_get_serial_sequence('legacy.purchase_orders', 'order_id'),
                                 (select max(order_id) from legacy.purchase_orders));

        insert into legacy.purchase_order_lines (order_id, line_no, sku, quantity, unit_price)
        select o.order_id,
               l,
               pg_catalog.format('SKU-%s', pg_catalog.lpad((1 + (o.order_id * 3 + l) % 20)::text, 3, '0')),
               1 + (o.order_id + l * 7) % 24,
               round(4.50 + ((o.order_id * 13 + l * 29) % 200) / 4.0, 2)
        from legacy.purchase_orders o
        cross join lateral pg_catalog.generate_series(1, 1 + (o.order_id % 4)::int) as l
        on conflict do nothing;

        update legacy.purchase_orders o
        set total = coalesce((select sum(l.quantity * l.unit_price)
                              from legacy.purchase_order_lines l
                              where l.order_id = o.order_id), 0);
        """;

    /// <summary>
    /// Three hundred entries over twelve days, then one of them written again: an audit table with no key
    /// holds exact duplicates, and a browser that pages it has to cope.
    /// </summary>
    private const string AuditLog =
        """
        insert into legacy.audit_log (logged_at, actor, action, entity, entity_key, details)
        select timestamptz '2026-06-01 07:00:00+00' + g * interval '37 minutes',
               case when g % 6 = 0 then 'system'
                    else coalesce((select e.email::text from legacy.employees e where e.employee_id = 1 + g % 40), 'unknown') end,
               (array['INSERT', 'UPDATE', 'UPDATE', 'DELETE', 'LOGIN', 'EXPORT'])[1 + g % 6],
               (array['purchase_orders', 'employees', 'stock_levels', 'warehouses'])[1 + g % 4],
               case when g % 5 = 0 then null else (1 + g % 30)::text end,
               case when g % 3 = 0 then null else pg_catalog.format('%s field(s) changed', 1 + g % 4) end
        from pg_catalog.generate_series(1, 300) as g;

        insert into legacy.audit_log (logged_at, actor, action, entity, entity_key, details)
        select a.logged_at, a.actor, a.action, a.entity, a.entity_key, a.details
        from legacy.audit_log a
        where a.logged_at = timestamptz '2026-06-01 07:00:00+00' + 42 * interval '37 minutes';
        """;

    /// <summary>Three sensors every six hours, for four days in each of the two partitions.</summary>
    private const string SensorReadings =
        """
        insert into legacy.sensor_readings (sensor_id, read_at, reading, unit)
        select s.sensor_id,
               t.read_at,
               round((s.base + 3 * pg_catalog.sin(extract(epoch from t.read_at)::float8 / 7200.0))::numeric, 3),
               s.unit
        from (values ('TEMP-FI1-01', 4.0, 'degC'),
                     ('TEMP-FI1-02', 5.5, 'degC'),
                     ('HUM-SE1-01', 41.0, '%RH')) as s(sensor_id, base, unit)
        cross join (
          select timestamptz '2026-03-01 00:00:00+00' + n * interval '6 hours' as read_at
          from pg_catalog.generate_series(0, 16) as n
          union all
          select timestamptz '2026-08-01 00:00:00+00' + n * interval '6 hours'
          from pg_catalog.generate_series(0, 16) as n
        ) as t
        """;

    private const string AppSettings =
        """
        insert into studio_sample.app_settings (setting_key, setting_value, value_type, updated_by, updated_at) values
          ('invoicing.default_currency', 'EUR', 'string', 'aino.virtanen', timestamptz '2026-02-02 10:15:00+00'),
          ('invoicing.payment_terms_days', '14', 'int', 'aino.virtanen', timestamptz '2026-02-02 10:16:00+00'),
          ('reminders.enabled', 'true', 'bool', null, timestamptz '2026-01-10 08:00:00+00'),
          ('reminders.first_after_days', '7', 'int', 'eero.korhonen', timestamptz '2026-03-18 14:40:00+00'),
          ('portal.maintenance_banner', '', 'string', null, timestamptz '2026-01-10 08:00:00+00'),
          ('exports.crm.endpoint', 'sftp://crm.acme.example/incoming', 'string', 'ops-bot', timestamptz '2026-05-05 05:05:00+00'),
          ('features.new_checkout', '{"rollout":0.25,"tenants":["acme"]}', 'json', 'helmi.nieminen', timestamptz '2026-09-01 12:00:00+00'),
          ('ops.max_parallel_exports', '4', 'int', 'ops-bot', timestamptz '2026-07-21 22:30:00+00')
        """;
}
