using System.Globalization;

using Marten;

using MartenStudio.Internal.Sql;
using MartenStudio.SampleDomain.Documents;
using MartenStudio.SampleDomain.Generation;
using MartenStudio.Services.Documents;
using MartenStudio.Services.Events;
using MartenStudio.Services.Projections;
using MartenStudio.Services.Query;
using MartenStudio.Services.Schema;

namespace MartenStudio.Integration.Tests.Generation;

/// <summary>
/// The studio against a hundred thousand documents and a hundred thousand events, generated by
/// <see cref="DemoDataGenerator" />.
/// </summary>
/// <remarks>
/// <para>
/// <b>Two things at once.</b> Half of these tests are about the generator - that it wrote what the plan
/// said, into the right collections, with the markers and the deliberate oddities that make the demo
/// database interesting. The other half are about the studio: that every screen's data call stays inside
/// <see cref="ResponsivenessBudgets" /> at this size. They share one fixture because generating the set
/// twice would double the slowest part of the suite.
/// </para>
/// <para>
/// <b>The budgets are not benchmarks.</b> They are several times a warm call, and what they catch is a
/// read whose cost is proportional to the collection - a sequential scan, an exact <c>count(*)</c> on a
/// navigation path, an offset page. Those miss by orders of magnitude, not by margins.
/// </para>
/// </remarks>
[Collection(GeneratedDataSuite.Name)]
public class MediumDataSetLiveTests(MediumDataSetFixture fixture) : IClassFixture<MediumDataSetFixture>
{
    private static CancellationToken Token => TestContext.Current.CancellationToken;

    private static void Write(string line) => TestContext.Current.TestOutputHelper?.WriteLine(line);

    private static DemoDataPlan Plan => DemoDataPlan.For(DemoDataSize.Medium);

    // ------------------------------------------------------------------------------------------------
    // What the generator wrote
    // ------------------------------------------------------------------------------------------------

    /// <summary>
    /// The plan is a promise: every collection has exactly the seeder's rows plus the generated ones.
    /// </summary>
    [PostgresFact]
    public async Task The_generated_set_is_exactly_what_the_plan_asked_for()
    {
        Write(string.Format(
            CultureInfo.InvariantCulture,
            "Medium: {0:N0} documents + {1:N0} events in {2:F1} s = {3:N0} rows/s",
            fixture.Counters.Documents,
            fixture.Counters.Events,
            fixture.GenerationTime.TotalSeconds,
            fixture.RowsPerSecond));

        fixture.Counters.Documents.Should().Be(Plan.DocumentTarget);
        fixture.Counters.Events.Should().Be(Plan.EventTarget);
        fixture.Counters.Streams.Should().Be(Plan.Streams);

        using var probe = new StudioResponsivenessProbe(fixture.Marten);

        // The seeder's own rows are still there, which is the whole reason the marker exists.
        (await probe.CountExactAsync("customer")).Value.Should().Be(Plan.Customers + 25);
        (await probe.CountExactAsync("order")).Value.Should().Be(Plan.Orders + 15);
        (await probe.CountExactAsync("invoice")).Value.Should().Be(Plan.Invoices + 6);
        (await probe.CountExactAsync("product")).Value.Should().Be(Plan.Products + 12);
        (await probe.CountExactAsync("vehicle")).Value.Should().Be(Plan.Vehicles + 10);
        (await probe.CountExactAsync("mediaasset")).Value.Should().Be(Plan.MediaAssets + 1);
    }

    /// <summary>
    /// The hierarchy survives the bulk loader: cars and trucks share a table and are told apart by
    /// <c>mt_doc_type</c>, which <c>BulkInsertAsync&lt;Car&gt;</c> has to write for the concrete type.
    /// </summary>
    /// <remarks>
    /// Worth its own test because it is the one thing about the bulk path that could have been silently
    /// wrong: Marten's <c>SubClassBulkLoader</c> hands the subclass documents to the <em>root's</em>
    /// loader, and a loader that wrote the root's alias would give a demo database a hundred thousand
    /// vehicles and no cars.
    /// </remarks>
    [PostgresFact]
    public async Task Bulk_inserted_subclasses_land_under_their_own_aliases()
    {
        using var probe = new StudioResponsivenessProbe(fixture.Marten);

        (_, CollectionRail rail) = await probe.RailAsync();

        CollectionInfo? car = rail.Find("car");
        CollectionInfo? truck = rail.Find("truck");

        car.Should().NotBeNull();
        truck.Should().NotBeNull();

        (await probe.CountExactAsync("car")).Value.Should().BeGreaterThan(1_000);
        (await probe.CountExactAsync("truck")).Value.Should().BeGreaterThan(1_000);
    }

    /// <summary>
    /// Generated documents carry the run marker and seeded ones do not, which is what makes truncation
    /// able to remove one and not the other.
    /// </summary>
    [PostgresFact]
    public async Task Generated_documents_carry_the_run_marker_and_seeded_ones_do_not()
    {
        await using IQuerySession session = fixture.Marten.Store.QuerySession();

        string runId = fixture.RunId;

        int generated = await session.Query<Customer>()
            .Where(x => x.GeneratedRun == runId)
            .CountAsync(Token);

        int seeded = await session.Query<Customer>()
            .Where(x => x.GeneratedRun == null)
            .CountAsync(Token);

        generated.Should().Be(Plan.Customers);
        seeded.Should().Be(25);
    }

    /// <summary>
    /// A handful of generated documents have JSON keys no CLR property matches, so the document editor's
    /// round-trip diff (D7) has real property loss to show.
    /// </summary>
    [PostgresFact]
    public async Task Some_generated_documents_carry_properties_the_type_does_not_have()
    {
        using var probe = new StudioResponsivenessProbe(fixture.Marten);
        using var documents = fixture.Marten.Documents();

        var id = DemoDataGenerator.CustomerId(fixture.RunId, 0).ToString();

        DocumentDetailResult result = await documents.Service.GetDocumentAsync(
            fixture.Marten.Scope, "customer", id, Token);

        result.Found.Should().BeTrue(result.NotFound?.Message);
        result.Detail!.Json.Should().Contain("LegacyNickname").And.Contain("MigratedFrom");

        // ... and an undrifted one does not, so the diff is about this document rather than about the type.
        var plain = DemoDataGenerator.CustomerId(fixture.RunId, Plan.DriftedDocuments + 10).ToString();

        DocumentDetailResult clean = await documents.Service.GetDocumentAsync(
            fixture.Marten.Scope, "customer", plain, Token);

        clean.Found.Should().BeTrue();
        clean.Detail!.Json.Should().NotContain("LegacyNickname");
    }

    /// <summary>
    /// One stream in <see cref="DemoDataPlan.PoisonStreamInterval" /> carries the SKU the demo's async
    /// projection throws on, so a running daemon accumulates dead letters in proportion to the data.
    /// </summary>
    [PostgresFact]
    public async Task Every_nth_stream_carries_the_event_the_async_projection_throws_on()
    {
        using var events = fixture.Marten.Resolve<IEventDataService>();

        Plan.PoisonedStreams.Should().BeGreaterThan(0);

        var streamId = DemoDataGenerator.StreamId(fixture.RunId, Plan.PoisonStreamInterval).ToString();

        EventPage page = await events.Service.GetStreamEventsAsync(
            fixture.Marten.Scope, streamId, afterVersion: 0, take: 50, Token);

        page.Error.Should().BeNull();
        page.Rows.Should().Contain(row => row.Json != null && row.Json.Contains("POISON", StringComparison.Ordinal));
    }

    // ------------------------------------------------------------------------------------------------
    // Responsiveness
    // ------------------------------------------------------------------------------------------------

    /// <summary>
    /// Every screen's first read, measured three times, median inside its budget.
    /// </summary>
    /// <remarks>
    /// One test rather than ten, because the measurements must not run concurrently with each other:
    /// two of them against one Postgres would be measuring contention. xunit runs the methods of a class
    /// in sequence, but a budget assertion that depends on that is a budget assertion that breaks the
    /// day somebody adds <c>[Trait]</c>-based parallelism.
    /// </remarks>
    [PostgresFact]
    public async Task Every_screens_read_stays_inside_its_budget()
    {
        using var probe = new StudioResponsivenessProbe(fixture.Marten);

        var report = new BudgetReport(Write);

        (TimeSpan railTime, CollectionRail rail) = await probe.RailAsync();
        rail.Error.Should().BeNull();
        report.Check("collections rail", railTime, ResponsivenessBudgets.CollectionsRail);

        (TimeSpan firstTime, DocumentPage first) = await probe.FirstPageAsync("customer");
        first.State.Should().Be(DocumentListState.Loaded, first.Error);
        first.Rows.Should().NotBeEmpty();
        report.Check("customer first page", firstTime, ResponsivenessBudgets.DocumentPage);

        (TimeSpan deepTime, DocumentPage deep) = await probe.DeepKeysetPageAsync("customer");
        deep.State.Should().Be(DocumentListState.Loaded, deep.Error);
        deep.Rows.Should().NotBeEmpty("the midpoint cursor has to land inside the collection");
        report.Check("customer deep keyset page", deepTime, ResponsivenessBudgets.DocumentPage);

        (TimeSpan recentTime, IReadOnlyList<RecentDocument> recent) = await probe.RecentAsync();
        recent.Should().NotBeEmpty();
        report.Check("_recent", recentTime, ResponsivenessBudgets.RecentDocuments);

        (TimeSpan feedTime, EventPage feed) = await probe.FeedFirstPageAsync();
        feed.Error.Should().BeNull();
        feed.Rows.Should().NotBeEmpty();
        report.Check("event feed first page", feedTime, ResponsivenessBudgets.EventFeedPage);

        long highest = await probe.HighestSequenceAsync() ?? 0;
        highest.Should().BeGreaterThan(0);

        (TimeSpan feedDeepTime, EventPage feedDeep) = await probe.FeedKeysetPageAsync(highest / 2);
        feedDeep.Error.Should().BeNull();
        feedDeep.Rows.Should().NotBeEmpty();
        report.Check("event feed keyset page", feedDeepTime, ResponsivenessBudgets.EventFeedPage);

        (TimeSpan streamsTime, StreamPage streams) = await probe.StreamsAsync();
        streams.Error.Should().BeNull();
        report.Check("stream list first page", streamsTime, ResponsivenessBudgets.StreamPage);

        (TimeSpan projectionsTime, ProjectionsView projections) = await probe.ProjectionsAsync();
        projections.Projections.Should().NotBeEmpty();
        report.Check("projections progress", projectionsTime, ResponsivenessBudgets.ProjectionsProgress);

        (TimeSpan tablesTime, SchemaTables tables) = await probe.SchemaTablesAsync();
        tables.Reason.Should().BeNull();
        tables.Tables.Should().NotBeEmpty();
        report.Check("schema Tables tab", tablesTime, ResponsivenessBudgets.SchemaTables);

        report.Unexpected.Should().BeEmpty(report.Because);
    }

    /// <summary>
    /// A free-text search over a hundred thousand documents is described rather than run, until somebody
    /// says to run it anyway.
    /// </summary>
    /// <remarks>
    /// Measured, but deliberately never executed: the withheld path is the one a browsing user hits, and
    /// its cost has to be the cost of parsing plus reading <c>pg_indexes</c>, not the cost of the scan it
    /// is refusing to do.
    /// </remarks>
    [PostgresFact]
    public async Task A_free_text_search_is_withheld_rather_than_run()
    {
        using var probe = new StudioResponsivenessProbe(fixture.Marten);

        (TimeSpan median, DocumentPage page) = await probe.WithheldSearchAsync("customer");

        Write(ResponsivenessBudgets.Line("withheld free-text search", median, ResponsivenessBudgets.DocumentPage));

        page.State.Should().Be(DocumentListState.BlockedByVerdict);
        page.Verdict.FilterLevel.Should().Be(IndexVerdictLevel.Red);
        page.Rows.Should().BeEmpty("a withheld search must not have run");
        median.Should().BeLessThan(ResponsivenessBudgets.DocumentPage);
    }

    /// <summary>
    /// Offset paging is capped: past <see cref="DocumentQueryBuilder.MaxOffset" /> the studio refuses and
    /// says to use the cursor, rather than asking Postgres to count past half a collection.
    /// </summary>
    [PostgresFact]
    public async Task Offset_paging_refuses_past_the_cap()
    {
        using var probe = new StudioResponsivenessProbe(fixture.Marten);

        (_, DocumentPage inside) = await probe.OffsetPageAsync("customer", DocumentQueryBuilder.MaxOffset);
        inside.State.Should().Be(DocumentListState.Loaded, inside.Error);

        (_, DocumentPage past) = await probe.OffsetPageAsync("customer", DocumentQueryBuilder.MaxOffset + 1);
        past.State.Should().Be(DocumentListState.Failed);
        past.Error.Should().Contain("keyset");
    }
}

/// <summary>
/// The xunit collection the generated-data suites share, so that two of them never measure at once.
/// </summary>
/// <remarks>
/// The assembly runs four collections in parallel. Two responsiveness suites against one Postgres would
/// be measuring each other, so they are named into one collection and therefore run in sequence. They
/// still run alongside the rest of the suite, which is why the budgets are generous rather than tight.
/// </remarks>
[CollectionDefinition(Name)]
public sealed class GeneratedDataSuite
{
    /// <summary>The collection name.</summary>
    public const string Name = "generated-data";
}
