namespace MartenStudio.Tests.Conventions;

/// <summary>
/// Asserts that the three GitHub Actions workflows are the generated ones, and that each still carries
/// the handful of lines its job actually depends on.
/// </summary>
/// <remarks>
/// <para>
/// All three files are generated from the <c>[GitHubActions]</c> attributes in
/// <c>build/Build.CI.GitHubActions.cs</c> (AGENTS.md hard rule 2). Nothing in the build ever reads them
/// back, so without this test a hand-edit would survive until the next build silently overwrote it - and
/// a wrong permission or a missing token would only be discovered by a release that failed.
/// </para>
/// <para>
/// The assertions are deliberately about <em>capability</em>, not formatting: that the key-minting job
/// has <c>id-token: write</c> and only <c>contents: read</c>, that the release job has the repository
/// write it needs and the token to use it, and that the CI job caches the Playwright browsers. A
/// reformat of the generator's YAML must not fail this test; a change to who can do what must.
/// </para>
/// </remarks>
public class WorkflowGenerationTests
{
    private const string GeneratedHeaderFirstLine =
        "# ------------------------------------------------------------------------------";

    private static string WorkflowsDirectory => RepositoryRoot.Combine(".github", "workflows");

    [Theory]
    [InlineData("build.yml")]
    [InlineData("publish.yml")]
    [InlineData("release.yml")]
    public void Every_workflow_this_repository_needs_exists(string fileName)
    {
        File.Exists(Path.Combine(WorkflowsDirectory, fileName)).Should().BeTrue(
            $"{fileName} is generated from a [GitHubActions] attribute; run `dotnet fallout Test` and commit it");
    }

    [Fact]
    public void Every_workflow_file_is_generated_and_none_is_hand_written()
    {
        var files = Directory.GetFiles(WorkflowsDirectory, "*.yml");

        files.Should().NotBeEmpty();

        foreach (var file in files)
        {
            var lines = File.ReadAllLines(file);

            // The header Fallout writes: a rule line, then the <auto-generated> marker.
            lines[0].Should().Be(GeneratedHeaderFirstLine, $"{Path.GetFileName(file)} must start with the " +
                "generated header - every workflow in this repository comes from a [GitHubActions] attribute");
            lines.Should().Contain(x => x.Contains("<auto-generated>", StringComparison.Ordinal),
                $"{Path.GetFileName(file)} must carry the <auto-generated> marker");
        }
    }

    /// <summary>
    /// The publish job is the only one that can mint a nuget.org key, so it must hold the OIDC permission
    /// and <em>only</em> read access to the repository.
    /// </summary>
    [Fact]
    public void The_publish_workflow_can_mint_a_key_and_cannot_write_to_the_repository()
    {
        var publish = ReadWorkflow("publish.yml");

        publish.Should().Contain("id-token: write");
        publish.Should().Contain("contents: read");
        publish.Should().NotContain("contents: write",
            "the workflow a nuget.org trusted publishing policy names must never also hold repository write");

        publish.Should().Contain("environment: nuget",
            "the GitHub environment is a second claim the trusted publishing policy matches on");
        publish.Should().Contain("NUGET_USER: lahma",
            "the policy owner's nuget.org profile name is public and travels as a plain env value");

        publish.Should().Contain("tags:");
        publish.Should().Contain("v*.*.*", "only a version tag may start the job that can mint a key");
        publish.Should().NotContain("paths:",
            "a path filter next to tags: evaluates over the tag commit's diff and can silently skip the run");
    }

    /// <summary>
    /// The release job writes the GitHub Release, so it needs repository write and the token to use it -
    /// and it must not be able to mint a publishing key.
    /// </summary>
    [Fact]
    public void The_release_workflow_can_write_releases_and_cannot_mint_a_key()
    {
        var release = ReadWorkflow("release.yml");

        release.Should().Contain("contents: write");
        release.Should().Contain("GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
            "EnableGitHubToken is what lets ICreateGitHubRelease authenticate against the GitHub API");
        release.Should().NotContain("id-token: write",
            "the workflow that holds repository write must never also be able to mint a nuget.org key");
        release.Should().Contain("v*.*.*");
    }

    [Fact]
    public void The_build_workflow_caches_the_playwright_browsers()
    {
        var build = ReadWorkflow("build.yml");

        build.Should().Contain("~/.cache/ms-playwright",
            "a Chromium download is ~150 MB and would otherwise be paid on every push and pull request");
        build.Should().Contain("~/.nuget/packages");
        build.Should().Contain("cancel-in-progress: true");
    }

    /// <summary>
    /// The CI workflow runs on every push and every pull request, including from a fork. It must not be
    /// able to mint a nuget.org publishing key, and it must not be able to write to the repository.
    /// </summary>
    [Fact]
    public void The_build_workflow_can_neither_mint_a_key_nor_write_to_the_repository()
    {
        var build = ReadWorkflow("build.yml");

        build.Should().NotContain("id-token: write",
            "only publish.yml may hold the OIDC permission; a workflow that runs on every pull request must not");
        build.Should().NotContain("contents: write");
        build.Should().Contain("contents: read",
            "naming one read permission makes every other permission 'none' for the run");
    }

    /// <summary>
    /// The nuget.org leg is one job running one target chain. More jobs would mean more OIDC exchanges
    /// racing the one-key-per-30-seconds rate limit, and a Publish that did not follow a Test in the same
    /// run would be publishing something nothing had verified.
    /// </summary>
    [Fact]
    public void The_publish_workflow_runs_compile_test_pack_and_publish_in_one_job()
    {
        var publish = ReadWorkflow("publish.yml");

        publish.Should().Contain("Compile Test Pack Publish");
    }

    private static string ReadWorkflow(string fileName) =>
        File.ReadAllText(Path.Combine(WorkflowsDirectory, fileName));
}
