using System.Security.Claims;

using JasperFx;

using Marten;

using MartenStudio.Integration.Tests.Browser;
using MartenStudio.Integration.Tests.Database;
using MartenStudio.Integration.Tests.Logging;
using MartenStudio.Internal.Sql;
using MartenStudio.SampleDomain;
using MartenStudio.Services;
using MartenStudio.Services.Database;
using MartenStudio.Services.Live;
using MartenStudio.Services.Relationships;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

using Npgsql;

namespace MartenStudio.Integration.Tests.Relationships;

/// <summary>
/// The sample's store with its relational neighbours - Quartz.NET's real job store in <c>quartz</c> and
/// the hand-made <c>legacy</c> schema - in a database of this class's own, seeded the way the sample
/// host seeds it, and read by three studios: one that may browse both schemas, one that may browse only
/// <c>quartz</c>, and one without <c>BrowseDatabase</c> at all.
/// </summary>
/// <remarks>
/// A database rather than a schema, for the reason <c>RelationalDemoFixture</c> gives: the demo is
/// anchored to <c>studio_sample</c> and creates the fixed schemas <c>quartz</c> and <c>legacy</c>, which
/// must not appear in the assembly's shared database under every other class's catalog reads.
/// </remarks>
/// <param name="postgres">The assembly's Postgres.</param>
public sealed class RelationshipsDemoFixture(PostgresFixture postgres) : IAsyncLifetime
{
    private MartenFixture? open;
    private MartenFixture? quartzOnly;
    private MartenFixture? closed;

    /// <summary>The database this fixture owns.</summary>
    public const string DatabaseName = "relationships_demo";

    /// <summary>The connection string of <see cref="DatabaseName" />.</summary>
    public string ConnectionString { get; private set; } = string.Empty;

    /// <summary>A studio with <c>BrowseDatabase</c> and both demo schemas browsable.</summary>
    public MartenFixture Open => open ?? throw NotRunning();

    /// <summary>A studio with <c>BrowseDatabase</c> and only <c>quartz</c> browsable: <c>legacy</c> is hidden.</summary>
    public MartenFixture QuartzOnly => quartzOnly ?? throw NotRunning();

    /// <summary>A studio without <c>BrowseDatabase</c>: the store's own schemas and nothing else.</summary>
    public MartenFixture Closed => closed ?? throw NotRunning();

    /// <summary>A customer that <c>legacy.customer_credit</c> has a row for.</summary>
    public Guid CreditedCustomerId { get; private set; }

    /// <inheritdoc />
    public async ValueTask InitializeAsync()
    {
        if (!DockerAvailability.IsAvailable)
        {
            return;
        }

        ConnectionString = await BrowserSuiteFixture.CreateDatabaseAsync(postgres, DatabaseName);

        open = await MartenFixture.CreateAsync(ConnectionString, SampleStore.DocumentSchema, configureStudio: static options =>
        {
            options.Capabilities = MartenStudioCapabilities.All();
            options.BrowsableSchemas.Add("quartz");
            options.BrowsableSchemas.Add("legacy");
        });

        // The sample's own seeder, which applies the relational demo last - exactly what the host runs.
        await open.SeedSampleDataAsync();

        quartzOnly = await MartenFixture.CreateAsync(ConnectionString, SampleStore.DocumentSchema, configureStudio: static options =>
        {
            options.Capabilities = MartenStudioCapabilities.All();
            options.BrowsableSchemas.Add("quartz");
        });

        closed = await MartenFixture.CreateAsync(ConnectionString, SampleStore.DocumentSchema);

        await using NpgsqlConnection connection = await OpenAsync();

        // A plain table in the store's own schema with a key of its own, pointing at the other plain table
        // the demo puts there - structure a studio without the capability still shows.
        await using (var create = new NpgsqlCommand(
                         """
                         create table if not exists studio_sample.app_setting_history (
                             id bigint generated by default as identity primary key,
                             setting_key text not null
                                 constraint app_setting_history_setting_key_fkey references studio_sample.app_settings (setting_key))
                         """,
                         connection))
        {
            await create.ExecuteNonQueryAsync();
        }

        await using var credited = new NpgsqlCommand(
            "select customer_id from legacy.customer_credit order by customer_id limit 1", connection);

        CreditedCustomerId = (Guid) (await credited.ExecuteScalarAsync())!;
    }

    /// <inheritdoc />
    public async ValueTask DisposeAsync()
    {
        foreach (MartenFixture? fixture in new[] { open, quartzOnly, closed })
        {
            if (fixture is not null)
            {
                await fixture.DisposeAsync();
            }
        }
    }

    /// <summary>An open connection to <see cref="DatabaseName" />, outside the studio.</summary>
    public async Task<NpgsqlConnection> OpenAsync()
    {
        var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync();
        return connection;
    }

    private static InvalidOperationException NotRunning() =>
        new("The relationships demo fixture is not running. A test that needs it must be a [PostgresFact].");
}

/// <summary>
/// Relationships over plain tables, live: the Quartz.NET graph, the legacy schema's NOT VALID key and its
/// key into a Marten document, the gate's three answers, the cross-schema "referenced by", and the shared
/// key read filtered per visitor.
/// </summary>
/// <param name="fixture">The seeded database and its three studios.</param>
public class RelationshipsDemoLiveTests(RelationshipsDemoFixture fixture) : IClassFixture<RelationshipsDemoFixture>
{
    private static readonly StudioScope Scope = new("default", string.Empty, null);

    private static CancellationToken Token => TestContext.Current.CancellationToken;

    [PostgresFact]
    public async Task The_quartz_graph_has_the_trigger_to_job_key_and_the_four_cascading_detail_keys()
    {
        RelationshipGraph graph = await GraphAsync(fixture.Open);

        graph.Error.Should().BeNull();
        graph.TablesUnavailable.Should().BeNull();

        RelationshipEdge triggers = graph.Edges.Should().ContainSingle(x =>
            graph.DisplayName(x.FromAlias) == "quartz.qrtz_triggers"
            && graph.DisplayName(x.ToAlias) == "quartz.qrtz_job_details").Subject;

        triggers.Column.Should().Be("job_name, job_group",
            "sched_name leads both primary keys, so it says nothing about which key this is");
        triggers.Columns.Should().Be("sched_name, job_name, job_group");
        triggers.FromIsTable.Should().BeTrue();
        triggers.ToIsTable.Should().BeTrue();

        List<string> cascades = [.. graph.Edges
            .Where(x => graph.DisplayName(x.ToAlias) == "quartz.qrtz_triggers" && x.OnDelete == "Cascade")
            .Select(x => graph.DisplayName(x.FromAlias))];

        cascades.Should().BeEquivalentTo(
        [
            "quartz.qrtz_blob_triggers",
            "quartz.qrtz_cron_triggers",
            "quartz.qrtz_simple_triggers",
            "quartz.qrtz_simprop_triggers",
        ]);

        graph.Tables.Should().Contain(x => x.QualifiedName == "quartz.qrtz_triggers" && x.RecognisedAs == "Quartz.NET");
        graph.Tables.Should().Contain(x => x.QualifiedName == "quartz.qrtz_locks",
            "a table with no key is still a table in a visible schema - the Tables view lists it");
    }

    [PostgresFact]
    public async Task The_legacy_not_valid_key_is_carried_as_not_validated()
    {
        RelationshipGraph graph = await GraphAsync(fixture.Open);

        RelationshipEdge edge = graph.Edges.Should().ContainSingle(x => x.ConstraintName == "purchase_order_lines_order_id_fkey").Subject;

        edge.Validated.Should().BeFalse("LegacySchema.sql adds it NOT VALID, after the one row that violates it");
        edge.State.Should().Be("not valid");
        RelationshipViews.StyleOf(edge).Should().Be("notvalid");

        graph.Edges.Where(x => x.ConstraintName != "purchase_order_lines_order_id_fkey")
            .Should().OnlyContain(static x => x.Validated, "every other key in the demo was checked when it was added");
    }

    [PostgresFact]
    public async Task The_legacy_key_into_a_marten_document_is_a_table_edge_with_its_cascade()
    {
        RelationshipGraph graph = await GraphAsync(fixture.Open);

        RelationshipEdge edge = graph.Edges.Should().ContainSingle(x => x.ConstraintName == "customer_credit_customer_id_fkey").Subject;

        graph.DisplayName(edge.FromAlias).Should().Be("legacy.customer_credit");
        edge.ToAlias.Should().Be("customer");
        edge.FromIsTable.Should().BeTrue();
        edge.ToIsTable.Should().BeFalse();
        edge.OnDelete.Should().Be("Cascade");

        graph.Unmatched.Should().NotContain(x => x.Name == "customer_credit_customer_id_fkey",
            "a key between a document and a table is drawable now");
    }

    [PostgresFact]
    public async Task Without_the_capability_no_quartz_or_legacy_node_appears_and_their_keys_into_the_store_are_counted()
    {
        RelationshipGraph graph = await GraphAsync(fixture.Closed);

        graph.Error.Should().BeNull();

        graph.Tables.Should().NotContain(static x => x.Schema == "quartz" || x.Schema == "legacy");
        graph.Edges.Should().OnlyContain(static x => !x.FromIsTable || x.FromAlias.StartsWith("studio_sample", StringComparison.Ordinal));

        graph.Withheld.Should().Contain(static x => x.VisibleEnd == "customer" && x.VisibleEndIsTarget,
            "legacy.customer_credit points at customer, and the count is all this visitor may have of it");

        AllText(graph).Should().NotContain("legacy").And.NotContain("quartz").And.NotContain("customer_credit");

        // Structure in the store's own schema needs no capability.
        RelationshipEdge settings = graph.Edges.Should().ContainSingle(x => x.ConstraintName == "app_setting_history_setting_key_fkey").Subject;
        graph.DisplayName(settings.FromAlias).Should().Be("studio_sample.app_setting_history");
        graph.DisplayName(settings.ToAlias).Should().Be("studio_sample.app_settings");
    }

    [PostgresFact]
    public async Task Referenced_by_counts_a_legacy_row_that_cascades_and_names_its_delete_action()
    {
        using MartenFixture.ScopedService<IRelationshipDataService> service = fixture.Open.Resolve<IRelationshipDataService>();

        ReferencedBy referenced = await service.Service.GetReferencedByAsync(
            Scope, "customer", fixture.CreditedCustomerId.ToString(), Token);

        referenced.Error.Should().BeNull();

        ReferencedByEntry credit = referenced.Entries.Should().ContainSingle(static x => x.IsTable).Subject;

        credit.Schema.Should().Be("legacy");
        credit.Table.Should().Be("customer_credit");
        credit.OnDelete.Should().Be("Cascade");
        credit.IsCounted.Should().BeTrue(credit.NotCounted ?? credit.Error);
        credit.Count.Should().Be(1, "customer_credit is keyed by the customer's id");
        credit.IsCapped.Should().BeFalse();
        referenced.Cap.Should().Be(RelationshipQueries.DefaultInboundCap, "the count is bounded, as every inbound count is");
        referenced.Withheld.Should().Be(0);

        referenced.DeleteConsequence().Should().Be(
            "Deleting this document also deletes 1 row in legacy.customer_credit (ON DELETE CASCADE).");

        fixture.Open.Services.GetRequiredService<StudioActionLogService>().GetLatest()
            .Should().NotContain(static x => x.Action == RelationshipDataService.ReferencesAction,
                "the count is a read the page makes on every load, not one the visitor asked for, and the ring is for what they did");
    }

    [PostgresTheory]
    [InlineData("quartz-only")]
    [InlineData("closed")]
    public async Task Referenced_by_for_a_visitor_whose_gate_hides_legacy_is_only_a_count(string which)
    {
        MartenFixture studio = which == "closed" ? fixture.Closed : fixture.QuartzOnly;

        using MartenFixture.ScopedService<IRelationshipDataService> service = studio.Resolve<IRelationshipDataService>();

        ReferencedBy referenced = await service.Service.GetReferencedByAsync(
            Scope, "customer", fixture.CreditedCustomerId.ToString(), Token);

        referenced.Error.Should().BeNull();
        referenced.Entries.Should().NotContain(static x => x.IsTable);
        referenced.Entries.Should().NotContain(static x => x.FromAlias.Contains("legacy", StringComparison.Ordinal));
        referenced.Withheld.Should().Be(1, "legacy.customer_credit's key is there, and this visitor is told only that");

        // The cascade still happens when this visitor deletes the customer, so the dialog says that it may -
        // naming neither the table nor its schema (D27).
        string? consequence = referenced.DeleteConsequence();

        consequence.Should().Be(
            "1 foreign key from a schema you are not shown points at this document; deleting it may delete or change rows there.");
        consequence.Should().NotContain("legacy").And.NotContain("customer_credit");
    }

    /// <summary>
    /// DB-6 review F1: opening a document again and again - with the rows countable, and with a
    /// <c>SqlConsoleRole</c> that may not select from the pointing table - writes nothing to the audit ring
    /// and nothing at Information or above to the log.
    /// </summary>
    /// <remarks>
    /// Before the fix, every open wrote a ring entry and a 9200 Information line per referencing table, and
    /// with the role lacking <c>SELECT</c> every open recorded a refusal - so a viewer paging through
    /// customers evicted real mutation audits from the 500-entry ring. The capture is proved to be listening:
    /// the service's own Debug line for the count is in it, and a direct, recorded row-gate ask for the same
    /// table does reach the ring.
    /// </remarks>
    [PostgresTheory]
    [InlineData(true)]
    [InlineData(false)]
    public async Task Opening_a_document_again_and_again_writes_no_audit_entry_and_no_information_line(bool roleMaySelect)
    {
        const string Role = "ms_relationships_demo_reader";
        const int Opens = 5;

        await ExecuteAsync(
            $$"""
            do $$
            begin
                if exists (select 1 from pg_roles where rolname = '{{Role}}') then
                    execute 'drop owned by {{Role}}';
                    execute 'drop role {{Role}}';
                end if;
            end
            $$;
            create role {{Role}} nologin;
            grant usage on schema studio_sample, quartz, legacy to {{Role}};
            grant select on all tables in schema studio_sample, quartz, legacy to {{Role}};
            {{(roleMaySelect ? string.Empty : $"revoke select on legacy.customer_credit from {Role};")}}
            """);

        try
        {
            LogCapture logs = new();

            await using ServiceProvider provider = Visitor(mayBrowse: true, role: Role, logs: logs);
            StudioActionLogService ring = provider.GetRequiredService<StudioActionLogService>();

            ReferencedBy? last = null;

            for (int i = 0; i < Opens; i++)
            {
                // A scope per open, as a circuit per page load would have.
                using IServiceScope scope = provider.CreateScope();

                last = await scope.ServiceProvider.GetRequiredService<IRelationshipDataService>()
                    .GetReferencedByAsync(Scope, "customer", fixture.CreditedCustomerId.ToString(), Token);
            }

            last!.Error.Should().BeNull();
            ReferencedByEntry credit = last.Entries.Should().ContainSingle(static x => x.IsTable).Subject;

            if (roleMaySelect)
            {
                credit.IsCounted.Should().BeTrue(credit.NotCounted ?? credit.Error);
                credit.Count.Should().Be(1);
            }
            else
            {
                credit.IsCounted.Should().BeFalse("the role may not select from it");
                credit.NotCounted.Should().NotBeNull().And.Contain(Role, "the row says why, naming the role");
                last.DeleteConsequence().Should().Be(
                    "Deleting this document may also delete rows in legacy.customer_credit (ON DELETE CASCADE, not counted).");
            }

            ring.GetLatest().Should().BeEmpty($"{Opens} opens of a document are not {Opens} things somebody did");
            logs.Lines.Where(static x => x.Level >= LogLevel.Information).Should().BeEmpty(
                "expected states never log above Debug, and page use must not flood the log");

            // The capture is listening: the count's own Debug line is there, once per open.
            logs.Lines.Count(static x => x.Level == LogLevel.Debug
                                         && x.Category.EndsWith(nameof(RelationshipDataService), StringComparison.Ordinal)
                                         && x.Message.Contains("legacy.customer_credit", StringComparison.Ordinal))
                .Should().Be(Opens);

            if (!roleMaySelect)
            {
                // And the ring is too: the same refusal asked for by somebody - recorded - is in it.
                using IServiceScope scope = provider.CreateScope();

                DatabaseRowAccessResult asked = await scope.ServiceProvider.GetRequiredService<DatabaseAccess>()
                    .RequireRowAccessAsync(Scope, "legacy", "customer_credit", cancellationToken: Token);

                asked.Refusal.Should().Be(DatabaseRefusal.NoPrivilege);
                ring.GetLatest().Should().ContainSingle(static x => !x.Succeeded && x.Target == "legacy.customer_credit");
            }
        }
        finally
        {
            await ExecuteAsync($"drop owned by {Role}; drop role {Role};");
        }
    }

    /// <summary>
    /// The key read is shared between visitors and filtered for each after the cache - proved with two
    /// visitors that differ only in what the write policy says to <c>BrowseDatabase</c>, one cache between
    /// them, and a key added between the two reads.
    /// </summary>
    /// <remarks>
    /// The refused visitor's graph is served from the read the admitted visitor's made - it cannot see the
    /// key added in between - and carries none of the admitted visitor's tables. A service with a cache of
    /// its own sees the new key, which is what makes the first half about the cache rather than about a
    /// read that never notices anything.
    /// </remarks>
    [PostgresFact]
    public async Task The_shared_key_read_is_filtered_per_visitor_after_the_cache()
    {
        StudioSnapshotCache shared = new(TimeProvider.System, TimeSpan.FromMinutes(5));

        await using ServiceProvider admitted = Visitor(mayBrowse: true);
        await using ServiceProvider refused = Visitor(mayBrowse: false);

        using IServiceScope admittedScope = admitted.CreateScope();
        using IServiceScope refusedScope = refused.CreateScope();

        RelationshipGraph first = await Build(admittedScope, shared).GetGraphAsync(Scope, Token);

        first.Error.Should().BeNull();
        first.Tables.Should().Contain(static x => x.QualifiedName == "legacy.customer_credit");
        first.Withheld.Should().BeEmpty("this visitor sees both schemas the database has besides the store's");

        await ExecuteAsync(
            "create table legacy.relationships_cache_probe (customer_id uuid references studio_sample.mt_doc_customer (id))");

        try
        {
            RelationshipGraph second = await Build(refusedScope, shared).GetGraphAsync(Scope, Token);

            second.Error.Should().BeNull();
            second.Tables.Should().NotContain(static x => x.Schema == "legacy" || x.Schema == "quartz",
                "the cached read holds legacy's keys, and this visitor's gate filters every one of them out");
            second.Withheld.Count(static x => x.VisibleEnd == "customer").Should().Be(1,
                "served from the read the first visitor made, before the probe's key existed");

            RelationshipGraph fresh = await Build(refusedScope, new StudioSnapshotCache(TimeProvider.System, TimeSpan.FromMinutes(5)))
                .GetGraphAsync(Scope, Token);

            fresh.Withheld.Count(static x => x.VisibleEnd == "customer").Should().Be(2,
                "a read of its own sees the probe's key - so the count above really was the shared one");
        }
        finally
        {
            await ExecuteAsync("drop table legacy.relationships_cache_probe");
        }
    }

    /// <summary>
    /// DB-6 review F7: the key read is cached under the database the resolver settled on, so an empty
    /// <c>?db=</c> and the same database named outright share one entry - proved as the per-visitor test
    /// proves sharing, with a key added between the two reads that only a read of its own would see.
    /// </summary>
    [PostgresFact]
    public async Task An_empty_db_and_the_same_database_named_outright_share_one_cached_key_read()
    {
        StudioSnapshotCache shared = new(TimeProvider.System, TimeSpan.FromMinutes(5));

        await using ServiceProvider visitor = Visitor(mayBrowse: true);
        using IServiceScope scope = visitor.CreateScope();

        string identity = (await scope.ServiceProvider.GetRequiredService<StudioScopeResolver>().ResolveAsync(Scope, null, Token))
            .Database.Id.Identity;

        identity.Should().NotBeNullOrEmpty();
        Scope.DatabaseId.Should().BeEmpty("the premise: the first read names no database");

        RelationshipGraph unnamed = await Build(scope, shared).GetGraphAsync(Scope, Token);
        unnamed.Error.Should().BeNull();

        const string Probe = "relationships_db_key_probe";

        await ExecuteAsync($"create table legacy.{Probe} (customer_id uuid references studio_sample.mt_doc_customer (id))");

        try
        {
            RelationshipGraph named = await Build(scope, shared).GetGraphAsync(Scope with { DatabaseId = identity }, Token);

            named.Error.Should().BeNull();
            named.Edges.Should().NotContain(static x => x.ConstraintName == Probe + "_customer_id_fkey",
                "the database named outright is the one the first read was cached under, so this is that read");

            RelationshipGraph fresh = await Build(scope, new StudioSnapshotCache(TimeProvider.System, TimeSpan.FromMinutes(5)))
                .GetGraphAsync(Scope with { DatabaseId = identity }, Token);

            fresh.Edges.Should().Contain(static x => x.ConstraintName == Probe + "_customer_id_fkey",
                "a read of its own sees the probe's key - so the one above really was served from the cache");
        }
        finally
        {
            await ExecuteAsync($"drop table legacy.{Probe}");
        }
    }

    // ----------------------------------------------------------------------------------------------

    private static async Task<RelationshipGraph> GraphAsync(MartenFixture studio)
    {
        studio.Services.GetRequiredService<StudioSnapshotCache>().InvalidatePrefix("default|");

        using MartenFixture.ScopedService<IRelationshipDataService> service = studio.Resolve<IRelationshipDataService>();

        return await service.Service.GetGraphAsync(Scope, Token);
    }

    /// <summary>Every name the graph would put on a screen, in one string.</summary>
    private static string AllText(RelationshipGraph graph) =>
        string.Join(
            "\n",
            graph.Tables.Select(static x => x.QualifiedName)
                .Concat(graph.Edges.Select(x => graph.DisplayName(x.FromAlias) + " " + graph.DisplayName(x.ToAlias) + " " + x.ConstraintName))
                .Concat(graph.Unmatched.Select(static x => x.Name + " " + x.From + " " + x.To + " " + x.Reason)));

    /// <summary>
    /// A studio over the fixture's database whose write policy says yes or no to <c>BrowseDatabase</c>,
    /// and yes to everything else - so two of them share every option and differ only in the visitor.
    /// </summary>
    /// <param name="mayBrowse">What the write policy says to <c>BrowseDatabase</c>.</param>
    /// <param name="role"><c>SqlConsoleRole</c>, or <see langword="null" /> to read as the store's own role.</param>
    /// <param name="logs">Where the studio's log goes, at every level; <see langword="null" /> for Warning and up, nowhere.</param>
    private ServiceProvider Visitor(bool mayBrowse, string? role = null, LogCapture? logs = null)
    {
        var services = new ServiceCollection();

        services.AddLogging(builder =>
        {
            if (logs is null)
            {
                builder.SetMinimumLevel(LogLevel.Warning);
            }
            else
            {
                builder.SetMinimumLevel(LogLevel.Trace);
                builder.AddProvider(logs);
            }
        });

        services.AddAuthorization();
        services.AddSingleton<AuthenticationStateProvider, SignedIn>();

        string connectionString = fixture.ConnectionString;

        services.AddMarten(options =>
        {
            SampleStore.Configure(options, connectionString);
            options.DatabaseSchemaName = SampleStore.DocumentSchema;
            options.Events.DatabaseSchemaName = SampleStore.DocumentSchema + "_events";
            options.AutoCreateSchemaObjects = AutoCreate.None;
        });

        services.AddMartenStudio(options =>
        {
            options.ReadOnly = false;
            options.Capabilities = MartenStudioCapabilities.All();
            options.BrowsableSchemas.Add("quartz");
            options.BrowsableSchemas.Add("legacy");
            options.WriteAuthorizationPolicy = "writers";
            options.SqlConsoleRole = role;
        });

        services.AddSingleton<IAuthorizationService>(new ResourcePolicy(resource =>
            mayBrowse || !string.Equals(resource.Capability, nameof(StudioCapability.BrowseDatabase), StringComparison.Ordinal)));

        return services.BuildServiceProvider();
    }

    private static RelationshipDataService Build(IServiceScope scope, StudioSnapshotCache cache) =>
        new(
            scope.ServiceProvider.GetRequiredService<IOptions<MartenStudioOptions>>(),
            scope.ServiceProvider.GetRequiredService<StudioScopeResolver>(),
            scope.ServiceProvider.GetRequiredService<ColumnCatalog>(),
            cache,
            scope.ServiceProvider.GetRequiredService<ILogger<RelationshipDataService>>(),
            scope.ServiceProvider.GetRequiredService<DatabaseAccess>(),
            scope.ServiceProvider.GetRequiredService<DatabaseCatalog>(),
            scope.ServiceProvider.GetRequiredService<StudioCapabilityGuard>(),
            TimeProvider.System);

    private async Task ExecuteAsync(string sql)
    {
        await using NpgsqlConnection connection = await fixture.OpenAsync();
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(Token);
    }

    /// <summary>Somebody is signed in; who they are is the policy's business, not this test's.</summary>
    private sealed class SignedIn : AuthenticationStateProvider
    {
        public override Task<AuthenticationState> GetAuthenticationStateAsync() =>
            Task.FromResult(new AuthenticationState(
                new ClaimsPrincipal(new ClaimsIdentity([new Claim(ClaimTypes.Name, "integration")], "test"))));
    }
}
